version: '3.9'
services:
  test-backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    depends_on:
      - adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
