version: '3.8'
services:
  dev:
    container_name: template-nestjs-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: yarn start
    networks:
      - backend
    # restart: unless-stopped # try this will restart if meet crash, but use pm2 instead
  db:
    image: postgres
    environment:
      - POSTGRES_USER=tusher
      - POSTGRES_PASSWORD=sazzadkueturp
      - POSTGRES_DB=backend-test
    ports:
      - 5432:5432
    depends_on:
      - pgadmin
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - 8888:80
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: sazzad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sazzad@gmail.com
networks:
  backend:
    driver: bridge
